"""Cache your API calls with a single line of code. No mocks, no fixtures. Just faster, cleaner code."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['doms', 'enable_cachy', 'disable_cachy']

# %% ../nbs/00_core.ipynb #fa68c98b
import base64,hashlib,httpx,json,fcntl
from fastcore.utils import *

# %% ../nbs/00_core.ipynb #527e76df
doms = ("chatgpt.com", "api.openai.com", "api.anthropic.com", "generativelanguage.googleapis.com", "api.deepseek.com",
    'api.fireworks.ai', 'openrouter.ai', 'api.groq.com', 'api.together.xyz', 'api.mistral.ai', 'api.x.ai')

# %% ../nbs/00_core.ipynb #09571365
def _should_cache(url, doms): return any(dom in str(url) for dom in doms)

# %% ../nbs/00_core.ipynb #c1e64d77
def _cache(key, cfp):
    if not Path(cfp).exists(): return None
    with open(cfp) as f:
        line = first(f, lambda l: json.loads(l)["key"] == key)
        return json.loads(line) if line else None

#| exports
def _write_cache(key, content, cfp, hdrs, status_code=200, binary=False):
    with open(cfp, "a") as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        f.write(json.dumps(dict(key=key, response=content, headers=hdrs, status_code=status_code, binary=binary))+"\n")

# %% ../nbs/00_core.ipynb #c1e64d77
def _cache(key, cfp):
    if not Path(cfp).exists(): return None
    with open(cfp) as f:
        line = first(f, lambda l: json.loads(l)["key"] == key)
        return json.loads(line) if line else None

#| exports
def _write_cache(key, content, cfp, hdrs, status_code=200, binary=False):
    with open(cfp, "a") as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        f.write(json.dumps(dict(key=key, response=content, headers=hdrs, status_code=status_code, binary=binary))+"\n")

# %% ../nbs/00_core.ipynb #3c7fca19
def _content(r):
    "Extract content from request."
    if not hasattr(r, '_content'): r.read()
    boundary = httpx._multipart.get_multipart_boundary_from_content_type(r.headers.get("Content-Type", "").encode())
    return r.content.replace(boundary, b"cachy-boundary") if boundary else r.content

# %% ../nbs/00_core.ipynb #a69ba22c
def _norm_content(r):
    "Normalize JSON bodies by sorting keys so semantically-equal payloads hash the same."
    c = _content(r)
    if 'json' in r.headers.get('content-type', '').lower():
        try: return json.dumps(json.loads(c), sort_keys=True).encode()
        except Exception: pass
    return c

def _key(r, is_stream=False):
    "Create a unique, deterministic id from the request `r`."
    return hashlib.sha256(f"{r.url.copy_remove_param('key')}{is_stream}".encode() + _norm_content(r)).hexdigest()[:8]

# %% ../nbs/00_core.ipynb #4cf3ccd9
def _is_text(res):
    "Check if response content type is text-like."
    ct = res.headers.get("content-type", "")
    return any(t in ct for t in ("text/", "json", "xml", "javascript", "html"))

def _res_hdrs(res, hdrs=None):
    if hdrs: return {k:v for k,v in res.headers.items() if k.lower() in hdrs}
    return {k:v for k,v in res.headers.items() if k.lower() != 'content-encoding'}

def _save_resp(key, raw, res, cfp, hdrs):
    headers = _res_hdrs(res, hdrs)
    if not (200 <= res.status_code < 300): return headers
    binary = not _is_text(res)
    content = base64.b64encode(raw).decode() if binary else raw.decode()
    _write_cache(key, content, cfp, headers, res.status_code, binary=binary)
    return headers

def _resp_from_cache(c, request):
    content = c['response']
    if c.get('binary'): content = base64.b64decode(content)
    return httpx.Response(status_code=c.get('status_code', 200), content=content, headers=c.get('headers'), request=request)

# %% ../nbs/00_core.ipynb #4c6a4afd
def _send(cfp, doms, self, request, debug=False, hdrs=None, **kwargs):
    is_stream = kwargs.get("stream")
    if not _should_cache(request.url, doms): return self._orig_send(request, **kwargs)
    key = _key(request, is_stream=is_stream)
    if c := _cache(key, cfp):
        if debug: print(f"🟢 HIT {key}\n{request.content}")
        return _resp_from_cache(c, request)
    res = self._orig_send(request, **kwargs)
    raw = res.read() if not is_stream else b''.join(list(res.iter_bytes()))
    if debug: print(f"🔴 MISS {key}\n{request.content}")
    headers = _save_resp(key, raw, res, cfp, hdrs)
    return httpx.Response(status_code=res.status_code, content=raw, headers=headers, request=request)

# %% ../nbs/00_core.ipynb #99a750c1
def _apply_sync_patch(cfp, doms, hdrs=None, debug=False):
    @patch
    def send(self:httpx._client.Client, request, **kwargs):
        return _send(cfp, doms, self, request, debug=debug, hdrs=hdrs, **kwargs)

# %% ../nbs/00_core.ipynb #76a06201
def _apply_async_patch(cfp, doms, hdrs=None, debug=False):
    @patch
    async def send(self:httpx._client.AsyncClient, request, **kwargs):
        is_stream = kwargs.get("stream")
        if not _should_cache(request.url, doms): return await self._orig_send(request, **kwargs)
        key = _key(request, is_stream=is_stream)
        if c := _cache(key, cfp):
            if debug: print(f"🟢 HIT {key}\n{request.content}")
            return _resp_from_cache(c, request)
        res = await self._orig_send(request, **kwargs)
        raw = await res.aread() if not is_stream else b''.join([c async for c in res.aiter_bytes()])
        if debug: print(f"🔴 MISS {key}\n{request.content}")
        headers = _save_resp(key, raw, res, cfp, hdrs)
        return httpx.Response(status_code=res.status_code, content=raw, headers=headers, request=request)

# %% ../nbs/00_core.ipynb #5b521d28
def enable_cachy(cache_dir=None, doms=doms, hdrs=None, debug=False):
    cfp = Path(cache_dir or find_file_parents("pyproject.toml") or ".") / "cachy.jsonl"
    cfp.touch(exist_ok=True)
    _apply_sync_patch(cfp, doms, hdrs, debug)
    _apply_async_patch(cfp, doms, hdrs, debug)

# %% ../nbs/00_core.ipynb #3be9fe57
def disable_cachy():
    if not hasattr(httpx._client.AsyncClient, '_orig_send'): return
    httpx._client.AsyncClient.send = httpx._client.AsyncClient._orig_send
    httpx._client.Client.send      = httpx._client.Client._orig_send

# %% ../nbs/00_core.ipynb #a8d53f6a
def enable_cachy(cache_dir=None, doms=doms, hdrs=None, debug=False):
    disable_cachy()
    if hdrs is None: hdrs=[]
    cfp = Path(cache_dir or find_file_parents("pyproject.toml") or ".") / "cachy.jsonl"
    cfp.touch(exist_ok=True)   
    _apply_sync_patch(cfp, doms, hdrs, debug)
    _apply_async_patch(cfp, doms, hdrs, debug)
