"""Cache your API calls with a single line of code. No mocks, no fixtures. Just faster, cleaner code.

Docs: https://AnswerDotAI.github.io/cachy/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['doms', 'norm_pats', 'enable_cachy', 'disable_cachy']

# %% ../nbs/00_core.ipynb #fa68c98b
import base64,hashlib,httpx,json,fcntl,requests
from httpx import AsyncClient
from fastcore.utils import *

# %% ../nbs/00_core.ipynb #527e76df
doms = ("chatgpt.com", "api.openai.com", "api.anthropic.com", "generativelanguage.googleapis.com", "api.deepseek.com",
    'api.fireworks.ai', 'openrouter.ai', 'api.groq.com', 'api.together.xyz', 'api.mistral.ai', 'api.x.ai', 'api.moonshot.ai')

# %% ../nbs/00_core.ipynb #09571365
def _should_cache(url, doms): return any(dom in str(url) for dom in doms)

# %% ../nbs/00_core.ipynb #c1e64d77
def _cache(key, cfp):
    if not Path(cfp).exists(): return None
    with open(cfp) as f:
        line = first(f, lambda l: json.loads(l)["key"] == key)
        return json.loads(line) if line else None

#| exports
def _write_cache(key, content, cfp, hdrs, status_code=200, binary=False):
    with open(cfp, "a") as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        f.write(json.dumps(dict(key=key, response=content, headers=hdrs, status_code=status_code, binary=binary))+"\n")

# %% ../nbs/00_core.ipynb #c1e64d77
def _cache(key, cfp):
    if not Path(cfp).exists(): return None
    with open(cfp) as f:
        line = first(f, lambda l: json.loads(l)["key"] == key)
        return json.loads(line) if line else None

#| exports
def _write_cache(key, content, cfp, hdrs, status_code=200, binary=False):
    with open(cfp, "a") as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        f.write(json.dumps(dict(key=key, response=content, headers=hdrs, status_code=status_code, binary=binary))+"\n")

# %% ../nbs/00_core.ipynb #3c7fca19
def _content(r):
    "Extract content from request."
    if not hasattr(r, '_content'): r.read()
    boundary = httpx._multipart.get_multipart_boundary_from_content_type(r.headers.get("Content-Type", "").encode())
    return r.content.replace(boundary, b"cachy-boundary") if boundary else r.content

# %% ../nbs/00_core.ipynb #8b2ff9ca
norm_pats = [
    (re.compile(r'/ipykernel_\d+/\d+\.py'), '/ipykernel_N/X.py'),
    (re.compile(r'<ipython-input-\d+-\w+>'), '<ipython-input>'),
    (re.compile(r'/var/folders/[\w|/]+'), '/tmp/tmpT'),
    (re.compile(r'/tmp/tmp\w+'), '/tmp/tmpX'),
    (re.compile(r'ipykernel_\d+'), 'ipykernel_N'),
    (re.compile(r'0x[0-9a-fA-F]{6,}'), '0xMEM'),
    (re.compile(r'line \d+, in'), 'line N, in'),
]

def _normalize(b):
    s = b.decode('utf-8', errors='replace')
    for pat,repl in norm_pats: s = re.sub(pat, repl, s)
    return s.encode('utf-8')

def _norm_content(r):
    "Normalize JSON bodies by sorting keys so semantically-equal payloads hash the same."
    c = _content(r)
    if 'json' in r.headers.get('content-type', '').lower():
        try: return json.dumps(json.loads(c), sort_keys=True).encode()
        except Exception: pass
    return c

def _key(r, is_stream=False):
    "Create a unique, deterministic id from the request `r`."
    return hashlib.sha256(f"{r.url.copy_remove_param('key')}{is_stream}".encode() + _normalize(_norm_content(r))).hexdigest()[:8]

# %% ../nbs/00_core.ipynb #4cf3ccd9
def _is_text(res):
    "Check if response content type is text-like."
    ct = res.headers.get("content-type", "")
    return any(t in ct for t in ("text/", "json", "xml", "javascript", "html"))

def _res_hdrs(res, hdrs=None):
    if hdrs: return {k:v for k,v in res.headers.items() if k.lower() in hdrs}
    return {k:v for k,v in res.headers.items() if k.lower() != 'content-encoding'}

def _save_resp(key, raw, res, cfp, hdrs):
    headers = _res_hdrs(res, hdrs)
    if not (200 <= res.status_code < 300): return headers
    binary = not _is_text(res)
    content = base64.b64encode(raw).decode() if binary else raw.decode()
    _write_cache(key, content, cfp, headers, res.status_code, binary=binary)
    return headers

def _resp_from_cache(c, request):
    content = c['response']
    if c.get('binary'): content = base64.b64decode(content)
    return httpx.Response(status_code=c.get('status_code', 200), content=content, headers=c.get('headers'), request=request)

# %% ../nbs/00_core.ipynb #4c6a4afd
def _check(request, doms, cfp, is_stream, debug, mk_resp=None):
    if not _should_cache(request.url, doms):
        if debug and debug!='miss': print(f"🔴 DOM MISS {request.url}\n{doms}")
        return None,None
    key = _key(request, is_stream=bool(is_stream))
    if c := _cache(key, cfp):
        if debug and debug!='miss': print(f"🟢 HIT {key}\n{request.content}")
        return key,(mk_resp or _resp_from_cache)(c, request)
    return key,None

def _finalize(key, raw, res, cfp, hdrs, request, debug):
    if debug: print(f"🔴 MISS {key}\n{request.content}")
    headers = _save_resp(key, raw, res, cfp, hdrs)
    return httpx.Response(status_code=res.status_code, content=raw, headers=headers, request=request)

def _send(cfp, doms, self, request, debug=False, hdrs=None, **kwargs):
    is_stream = kwargs.get("stream")
    key,cached = _check(request, doms, cfp, is_stream, debug)
    if cached is not None: return cached
    if key is None: return self._orig_send(request, **kwargs)
    res = self._orig_send(request, **kwargs)
    raw = res.read() if not is_stream else b''.join(list(res.iter_bytes()))
    return _finalize(key, raw, res, cfp, hdrs, request, debug)

async def _asend(cfp, doms, self, request, debug=False, hdrs=None, **kwargs):
    is_stream = kwargs.get("stream")
    key,cached = _check(request, doms, cfp, is_stream, debug)
    if cached is not None: return cached
    if key is None: return await self._orig_send(request, **kwargs)
    res = await self._orig_send(request, **kwargs)
    raw = await res.aread() if not is_stream else b''.join([c async for c in res.aiter_bytes()])
    return _finalize(key, raw, res, cfp, hdrs, request, debug)

async def _ahandle(cfp, doms, self, request, debug=False, hdrs=None):
    is_stream = request.extensions.get('stream', False)
    key,cached = _check(request, doms, cfp, is_stream, debug)
    if cached is not None: return cached
    if key is None: return await self._orig_handle_async_request(request)
    res = await self._orig_handle_async_request(request)
    raw = await res.aread()
    return _finalize(key, raw, res, cfp, hdrs, request, debug)

# %% ../nbs/00_core.ipynb #a1340ce5
def _req_resp_from_cache(c, request):
    "Build a `requests.Response` from cache entry `c`."
    res = requests.Response()
    res.status_code = c.get('status_code', 200)
    res._content = base64.b64decode(c['response']) if c.get('binary') else c['response'].encode()
    res.headers = requests.structures.CaseInsensitiveDict(c.get('headers') or {})
    res.encoding = requests.utils.get_encoding_from_headers(res.headers)
    res.url,res.request = request.url,request
    return res

def _req_send(cfp, doms, self, request, debug=False, hdrs=None, **kwargs):
    body = request.body or b''
    hreq = httpx.Request(request.method, request.url, headers=dict(request.headers), content=body.encode() if isinstance(body,str) else body)
    key,cached = _check(hreq, doms, cfp, kwargs.get('stream'), debug, mk_resp=_req_resp_from_cache)
    if cached is not None: return cached
    if key is None: return self._orig_send(request, **kwargs)
    res = self._orig_send(request, **kwargs)
    if debug: print(f"🔴 MISS {key}\n{body}")
    res.headers = requests.structures.CaseInsensitiveDict(_save_resp(key, res.content, res, cfp, hdrs))
    return res

def _apply_requests_patch(cfp, doms, hdrs=None, debug=False):
    @patch
    def send(self:requests.adapters.HTTPAdapter, request, **kwargs):
        return _req_send(cfp, doms, self, request, debug=debug, hdrs=hdrs, **kwargs)

# %% ../nbs/00_core.ipynb #99a750c1
def _apply_sync_patch(cfp, doms, hdrs=None, debug=False):
    @patch
    def send(self:httpx._client.Client, request, **kwargs): return _send(cfp, doms, self, request, debug=debug, hdrs=hdrs, **kwargs)

# %% ../nbs/00_core.ipynb #76a06201
def _apply_async_patch(cfp, doms, hdrs=None, debug=False):
    @patch
    async def send(self:AsyncClient, request, **kwargs): return await _asend(cfp, doms, self, request, debug=debug, hdrs=hdrs, **kwargs)

def _apply_aiohttp_patch(cfp, doms, hdrs=None, debug=False):
    try: from litellm.llms.custom_httpx.aiohttp_transport import LiteLLMAiohttpTransport
    except ImportError: return
    @patch
    async def handle_async_request(self:LiteLLMAiohttpTransport, request):
        return await _ahandle(cfp, doms, self, request, debug=debug, hdrs=hdrs)

# %% ../nbs/00_core.ipynb #d5c98e90
def enable_cachy(cache_dir=None, doms=doms, hdrs=None, debug=False):
    disable_cachy()
    if hdrs is None: hdrs=[]
    cfp = Path(cache_dir or find_file_parents("pyproject.toml") or ".") / "cachy.jsonl"
    cfp.touch(exist_ok=True)
    _apply_sync_patch    (cfp, doms, hdrs, debug)
    _apply_async_patch   (cfp, doms, hdrs, debug)
    _apply_requests_patch(cfp, doms, hdrs, debug)
    _apply_aiohttp_patch (cfp, doms, hdrs, debug)

# %% ../nbs/00_core.ipynb #3be9fe57
def disable_cachy():
    if hasattr(AsyncClient, '_orig_send'):
        AsyncClient.send  = AsyncClient._orig_send
        httpx.Client.send = httpx.Client._orig_send
    if hasattr(requests.adapters.HTTPAdapter, '_orig_send'):
        requests.adapters.HTTPAdapter.send = requests.adapters.HTTPAdapter._orig_send
    try: from litellm.llms.custom_httpx.aiohttp_transport import LiteLLMAiohttpTransport
    except ImportError: return
    if hasattr(LiteLLMAiohttpTransport, '_orig_handle_async_request'):
        LiteLLMAiohttpTransport.handle_async_request = LiteLLMAiohttpTransport._orig_handle_async_request
