name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install git+https://github.com/AnswerDotAI/fastcore.git
          pwd
          ls -la
          python -c "from fastcore.utils import find_file_parents; print('result:', find_file_parents('pyproject.toml'))"
      - uses: answerdotai/workflows/nbdev3-ci@master
        with:
          pre: 1
